import { Checkout } from "./views";
import { CheckOutData, CheckoutItemRadio } from "./types";
import {
  schemaCheckoutForm,
  defaultValuesForm,
  phoneRegex,
  calculateTotals,
} from "./utils";
import { useGoHome } from "./hooks";
import {
  FormOptions,
  BillingDetails,
  ShippingDetails,
  PaymentsDetails,
  Summary,
  ItemsSummary,
  ItemPreviewSummary,
  Totals,
  TotalRow,
  OrderRecap,
  OrderRecapContainer,
  ItemsRecap,
  OrderDetailRecap,
  OrderTotalRecap,
  OrderDetailItem,
} from "./components";

export {
  Checkout,
  type CheckOutData,
  type CheckoutItemRadio,
  schemaCheckoutForm,
  defaultValuesForm,
  phoneRegex,
  FormOptions,
  BillingDetails,
  ShippingDetails,
  PaymentsDetails,
  Summary,
  ItemsSummary,
  ItemPreviewSummary,
  Totals,
  TotalRow,
  calculateTotals,
  FormOptions,
  BillingDetails,
  ShippingDetails,
  PaymentsDetails,
  Summary,
  ItemsSummary,
  ItemPreviewSummary,
  Totals,
  calculateShipping,
  calculateVat,
  calculateGrandTotal,
  TotalRow,
  OrderRecap,
  OrderRecapContainer,
  ItemsRecap,
  OrderDetailRecap,
  OrderTotalRecap,
  OrderDetailItem,
  useGoHome,
};
